name: diaryapp
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  go_router:
  flutter:
    sdk: flutter
  flutter_chat_ui: ^1.6.9

  flutter_chat_types: ^3.6.2
  dart_openai: ^4.0.0
  flutter_dotenv: ^5.1.0

  image_picker: ^0.8.4+4
  table_calendar: ^3.0.9



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  assets:
    - .env
  uses-material-design: true
